name: context_menus
description: A package to show context menus on right-click or long-press.
version: 1.0.2
homepage: https://github.com/gskinnerTeam/flutter-context-menu

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
